version: '3.3'
services:

  mysql:
    image: 'mysql:5.6'
    ports:
      - '3306'
    volumes:
      - .:/opt
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app

  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile
      context: ./
    ports:
      - "80"
    links:
      - api

  api:
    build:
      dockerfile: ./docker/api/Dockerfile
      context: ./
    links:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: app
      DB_USERNAME: root
      DB_PASSWORD: password
    volumes:
      - .:/opt
